### PR TITLE
Fix MaterialExplorer

### PR DESCRIPTION
**Pull request by Leva7**
Related to #32 

The example application was not compiling due to some issues. That has been fixed by doing the following:

* Removing the `rn-cli.config.js` file which was giving trouble by searching for `react-native/packager/blacklist`, which doesn't seem to exist anymore 
* Adding the application dependencies to the `package.json` file. I've decided to also include the actual `material-native` library to make the example clearer and to allow users to take it out of the folder. If you're not fine with that, I'll revert it.

Some side effects:
* Removal of `rn-cli.config.js` also disabled the building from root directory, so that needs to be addressed
* The Java package name turned from `org.redwerks.opensource.materialexplorer` to `com.materialexplorer`. That it because I've created a brand new React project to make everything as up-to-date as possible
* I followed the instructions for installing React Native Vector Icons and ended up removing the font files in the directory and downloading them with Gradle. That's the recommended way to go, so I think that it's a good thing. It also makes the folder weigh less when cloning the repository.

I'm not quite sure as to what happened to the iOS version of the example. I'm not into iOS development, so I didn't touch that folder, but since the `rn-cli.config.js` was deleted, the example in the README might be invalid. That also needs to be addressed

### CODE REVIEW

**Comment by dantman** [comment]
MaterialExplorer's `package.json` wasn't meant as an example of how to use the library. `rn-cli.config.js` was used so that MaterialExplorer could actually be used during development. If the explorer depends on `material-native` instead of using the source from the repo you check out, then live reload doesn't work and you have to purge and re-install the example over and over.

**Comment by Leva7** [comment]
But is the example functional right now with the latest tools? Because I couldn't figure out how to compile it

**Comment by dantman** [comment]
Right now the devDeps/example package isn't depending on the latest version, it's requiring `"react-native": "^0.43.4",` which is was built against (react-native examples generally never run on any version other than the one they were built against due to how unstable react-native is).

**Comment by Leva7** [comment]
So why isn't this particular version of RN written in the dependencies of `package.json`?

**Comment by dantman** [comment]
@Leva7 It is in the devDependencies of the root package.json, it's not in the example's package because if it were then `react-native` would be installed in the examples folder instead of the root and the `material-native` code in the root would not be able to require `react-native`, breaking the app.

**Pull request closed without merging**
